version: '3'

services:
  backend:
    build:
      context: ./Backend
      args:
        DJANGO_ALLOWED_HOSTS: 127.0.0.1
        DJANGO_SECRET_KEY: 'wefwvefbrbsdcwc6868g'
        DJANGO_CORS_ORIGIN_WHITELIST: http://127.0.0.1
    command: gunicorn home.wsgi.prod --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./Frontend
      args:
        API_URL: http://127.0.0.1
    volumes:
      - build_folder:/frontend/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend


volumes:
  build_folder:
